# Generated by Django 4.2.4 on 2023-08-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpswd',
        ),
    ]
