# Generated by Django 4.2.4 on 2023-08-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_brand', models.CharField(max_length=20)),
                ('mobile_model', models.CharField(max_length=20)),
                ('mobile_ram', models.CharField(max_length=10)),
                ('mobile_storage', models.CharField(max_length=10)),
                ('mobile_price', models.IntegerField()),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
